services:
  - type: web
    name: msc-offline-registration
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: msc-event-db
          property: connectionString
      - key: APP_URL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_INITIAL_PASSWORD
        sync: false

databases:
  - name: msc-event-db
    databaseName: msc_event_db
    user: msc_user
    plan: free
